#pragma once

#include <algorithm>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <map>
#include <unordered_map>
#include <stdexcept>
#include <string>
#include <sstream>
#include <vector>
#include <memory>

#include <assert.h>
#include <limits.h>
#include <math.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdint.h>
#include <time.h>

#include <entt.hpp>
#include <json.h>
#include <stb_image.h>
#include <json.h>

#include "FileSystem.h"
#include "HardwareInfo.h"
#include "../GameWindow.h"
#include "../Platform.h"
#include "../../Application/Application.h"
#include "../../Application/Config.h"
#include "../../Application/GameLoop.h"
#include "../../Application/TimeStep.h"
#include "../../Audio/Audio.h"
#include "../../Audio/AudioTypes.h"
#include "../../Audio/AudioEngine.h"
#include "../../Debug/Log.h"
#include "../../Debug/Profile.h"
#include "../../Debug/DebugUI.h"
#include "../../Graphics/AnimatedSprite.h"
#include "../../Graphics/BatchRenderer.h"
#include "../../Graphics/Buffer.h"
#include "../../Graphics/Camera.h"
#include "../../Graphics/CircleRenderer.h"
#include "../../Graphics/Color.h"
#include "../../Graphics/ColorList.h"
#include "../../Graphics/Font.h"
#include "../../Graphics/Graphics.h"
#include "../../Graphics/GraphicTypes.h"
#include "../../Graphics/LineRenderer.h"
#include "../../Graphics/PointRenderer.h"
#include "../../Graphics/Shader.h"
#include "../../Graphics/Sprite.h"
#include "../../Graphics/SpriteAtlas.h"
#include "../../Graphics/SpriteFont.h"
#include "../../Graphics/SpriteRenderer.h"
#include "../../Graphics/Texture.h"
#include "../../Graphics/VertexArray.h"
#include "../../Input/Gamepad.h"
#include "../../Input/Keyboard.h"
#include "../../Input/Mouse.h"
#include "../../Input/InputManager.h"
#include "../../Math/LineSegment.h"
#include "../../Math/Math.h"
#include "../../Math/Matrix.h"
#include "../../Math/Random.h"
#include "../../Math/Transformable.h"
#include "../../Math/Vector2.h"
#include "../../Resources/Resource.h"
#include "../../Resources/ResourceCache.h"
#include "../../Resources/ResourceManager.h"
#include "../../Utils/Png/Png.h"
#include "../../Utils/Text/Text.h"
#include "../../Utils/Wave/Wave.h"